# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.DateTimeField(default=django.utils.timezone.now)),
                ('distance', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humity', models.IntegerField()),
                ('light', models.IntegerField()),
            ],
            options={
                'ordering': ('-title', '-temperature'),
            },
        ),
    ]
