# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_data_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='slug',
        ),
    ]
