# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='title'),
            preserve_default=False,
        ),
    ]
